apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "freshrss.labels" . | nindent 4 }}
    {{- with .Values.ingress.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
stringData:
 {{- if .Values.oidc.secrets }}
  OIDC_CLIENT_SECRET: {{ .Values.oidc.secrets.clientSecret | default "" }}
  OIDC_CLIENT_CRYPTO_KEY: {{ .Values.oidc.secrets.clientCryptoKey | default "" }}
  {{- end }}